import "~/styles/globals.css";

import { Nunito } from "next/font/google";
import { cn } from "~/lib/utils";
import { MenuIcon, ShoppingCartIcon } from "lucide-react";

import logoImg from "../../public/logo.png";
import Image from "next/image";

const nunitoFont = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "min-h-screen bg-background font-sans text-foreground antialiased",
        nunitoFont.variable,
      )}
    >
      <body>
        <div className="bg-primary p-2 text-center text-primary-foreground">
          Naujiena! Daug nauju zaidimu!
        </div>

        <nav className="flex justify-between p-4">
          <Image
            src={logoImg}
            alt="tavo mama"
            className="h-12 min-w-0 max-w-12 shrink"
          />
          <div className="flex shrink-0 items-center gap-6">
            <ShoppingCartIcon className="h-10 w-10" />
            <MenuIcon className="h-10 w-10" />
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
