import "~/styles/globals.css";

import { Nunito } from "next/font/google";
import { cn } from "~/lib/utils";
import { MenuIcon, ShoppingCartIcon } from "lucide-react";

import logoImg from "../../public/logo.png";
import Image from "next/image";
import { BiLogoFacebookCircle, BiLogoInstagram } from "react-icons/bi";
import Link from "next/link";

const nunitoFont = Nunito({
  subsets: ["latin"],
  variable: "--font-nunito",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={cn(
        "min-h-screen bg-background font-sans text-foreground antialiased",
        nunitoFont.variable,
      )}
    >
      <body>
        <div className="bg-primary p-2 text-center text-primary-foreground">
          Naujiena! Daug nauju zaidimu!
        </div>

        <nav className="flex justify-between p-4">
          <Image
            src={logoImg}
            alt='"Žaidimų pieva" logotipas'
            className="h-12 min-w-0 max-w-12 shrink"
          />
          <div className="flex shrink-0 items-center gap-6">
            <ShoppingCartIcon className="h-10 w-10" />
            <MenuIcon className="h-10 w-10" />
          </div>
        </nav>

        {children}

        <footer className="flex flex-wrap items-center justify-between gap-y-4 p-2 px-6">
          <div className="flex items-center">
            <Image
              src={logoImg}
              alt='"Žaidimų pieva" logotipas'
              className="h-10 w-10"
            />
            <p className="-mb-1 text-xl font-bold">Žaidimų Pieva</p>
          </div>

          <BiLogoInstagram className="text-3xl" />
          <BiLogoFacebookCircle className="text-3xl" />

          <ul className="flex w-full justify-between font-bold">
            <li>
              <Link href="/">Pagrindinis</Link>
            </li>
            <li>
              <Link href="/zaidimai">Žaidimai</Link>
            </li>
            <li>
              <Link href="/kontaktai">Kontaktai</Link>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
